Add

diff --git a/.github/workflows/main_backend-bazaar.yml b/.github/workflows/main_backend-bazaar.yml
--- a/.github/workflows/main_backend-bazaar.yml
+++ b/.github/workflows/main_backend-bazaar.yml
@@ -1,6 +1,3 @@
-# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
-# More GitHub Actions for Azure: https://github.com/Azure/actions
-
 name: Build and deploy Node.js app to Azure Web App - backend-bazaar
 
 on:
@@ -21,15 +18,13 @@ jobs:
         with:
           node-version: '18.x'
 
-      - name: Install dependencies
+      - name: Install dependencies and set Chromium path
         run: |
-          sudo apt-get update -y
-          sudo apt-get install -y libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libasound2
+          sudo apt-get update -yy
+          sudo apt-get install -yy libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libasound2
           npm install
-          npx puppeteer install
-
-      - name: Set up CHROME_PATH environment variable
-        run: echo "CHROME_PATH=$(npx puppeteer browsers path chrome)" >> $GITHUB_ENV
+          npx puppeteer browsers install chrome
+          echo "CHROME_PATH=$(npx puppeteer browsers path chrome)" >> $GITHUB_ENV
 
       - name: Zip artifact for deployment
         run: zip release.zip ./* -r
@@ -63,13 +58,22 @@ jobs:
         uses: azure/login@v1
         with:
           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D4F8E456517E4E9DA84A47D590F5A717 }}
-          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FD0F63922F1747FC94B55EE08F714806 }}
-          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F2CFAEFEB1054EDE8E8A523931559234 }}
+          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F2CFAEFEB1054EDE8E8A523931559234 }}
+          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FD0F63922F1747FC94B55EE08F714806 }}
 
-      - name: 'Deploy to Azure Web App'
+      - name: Deploy to Azure Web App
         id: deploy-to-webapp
         uses: azure/webapps-deploy@v2
         with:
           app-name: 'backend-bazaar'
           slot-name: 'Production'
           package: .
+
+      - name: Check Chrome path
+        run: which chromium-browser || which google-chrome || echo "Chrome not found"
+
+      - name: Run the application
+        run: |
+          export CHROME_PATH=$(which chromium-browser || which google-chrome || echo $CHROME_PATH)
+          echo "CHROME_PATH=$CHROME_PATH"
+          npm start
